language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_install: cd get_libsodium && ./get_libsodium.sh

env:
    - SODIUM_LIB_DIR=get_sodium/dest/usr/local/lib SODIUM_STATIC=yes
