language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_install: cd build && ./build_libsodium.sh

env:
    - SODIUM_LIB_DIR=build/libsodium_lib/src/libsodium SODIUM_STATIC=yes
