language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_install: ./build/build_libsodium.sh

env:
    - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:build/libsodium-root
