language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_install: cd sodium && ./get_libsodium.sh

env:
    - SODIUM_LIB_DIR=sodium/dest SODIUM_STATIC=yes
