language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - os: osx
    - rust: nightly

before_install: ./scripts/get_deps.sh "$TRAVIS_BUILD_DIR"
env: SODIUM_LIB_DIR="$TRAVIS_BUILD_DIR/usr/local/lib" SODIUM_STATIC=yes

script: ./scripts/build.sh "$TRAVIS_BUILD_DIR"

deploy:
  provider: script
  script: ./scripts/deploy.sh "$TRAVIS_BUILD_DIR"
  on:
    tags: true
