language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_install: ./build/build_libsodium.sh

env:
    - SODIUM_LIB_DIR=build/libsodium_lib
    - SODIUM_STATIC=yes
