[package]
name = "passthesalt"
version = "0.1.0"
authors = ["icasdri <icasdri@gmail.com>"]

[dependencies]
libpassthesalt = { path = "libpassthesalt" }

[dependencies.clap]
version = "2"
default-features = false
